### ISSUE TITLE
Can't upload subdirectory.

### ISSUE THREAD

**Issue by dev-gwang** [artefactory/nautilus-sftp-gateway#62] opened 2020-08-05 06:44 UTC
**Describe the bug**
When i create (or upload) a subdirectory on SFTP, nautilus-sftp-gateway service is crashed. 

**To Reproduce**
1. connect to sftp server (SFTP Protocol)
2. make directory A.
3. make directory A/B

**Screenshots**
![image](https://user-images.githubusercontent.com/14958650/89380247-29edac00-d732-11ea-9254-61f0cd583613.png)

**Desktop**
 - OS: CentOS7

**Comment by Cedric-Magnan** [comment] 2020-08-05 10:07
@dev-gwang 
Thanks for noticing this issue.
This issue was also notified by our internal team and seem to be fixed on the latest version of the SFTP Gateway.
Can you update your code with the latest commit from master and try again if that's not already done ?

**Comment by dev-gwang** [comment] 2020-08-05 13:41
@Cedric-Magnan 
Hello! Thank you so much for your feedback.
I have used the latest commit, and nothing has been modified by me.
![image](https://user-images.githubusercontent.com/14958650/89419353-3c84d700-d76c-11ea-8f86-352c08d90abf.png)

Please let me know if there is anything else I need to check.
Thank you!

**Comment by Cedric-Magnan** [comment] 2020-08-05 15:04
@dev-gwang 

I have just updated the master branch.
The correct behavior should now be implemented.
Can you test it and let me know if the issue is fixed ?

**Comment by dev-gwang** [comment] 2020-08-06 07:45
@Cedric-Magnan 

1. create subfolder
- sftp
![image](https://user-images.githubusercontent.com/14958650/89504771-8b318000-d803-11ea-8e8e-9b8f7149f4c7.png)
- nautilus-sftp-gateway service
![image](https://user-images.githubusercontent.com/14958650/89504844-a603f480-d803-11ea-8584-bea4a37c331c.png)

2. send file
![image](https://user-images.githubusercontent.com/14958650/89504914-c03dd280-d803-11ea-8db5-3fc880fe63df.png)
![image](https://user-images.githubusercontent.com/14958650/89504953-d186df00-d803-11ea-9dc7-38f1c6d3bb9b.png)

3. gcs
![image](https://user-images.githubusercontent.com/14958650/89505081-0135e700-d804-11ea-8a70-c89e04ccd211.png)

I checked that the desired motion was working properly.
Thank you

**Closed** 2020-08-06 07:51 UTC
Labels: bug
